### ISSUE TITLE
name'DataHolder' is not defined

### ISSUE THREAD

**Issue by lisitian080516** [pps-lab/fl-analysis#3]
when I run python -m src.main -c config.yml, there will be a NameError: name 'DataHolder' is not defined. The I found the src.torch_compat.py is missed.

**Comment by hiddely** [comment]
Thanks for pointing this out! There was an unused import referring to `src.torch_compat.py`. Commit [c0b799](https://github.com/pps-lab/fl-analysis/commit/c0b799f6415a35a91e7515d58d03128830b766db) fixes the imports.

Please let me know if you find any other issue!
